// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdcqukyh8dE7mmfVmmxPVASG7tpQaZ5w',
    appId: '1:707196677230:web:73cbc5d846321bbefc0a7f',
    messagingSenderId: '707196677230',
    projectId: 'tik-tok-dani1552',
    authDomain: 'tik-tok-dani1552.firebaseapp.com',
    storageBucket: 'tik-tok-dani1552.appspot.com',
    measurementId: 'G-L616Z2F1QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezPCZqg2-rcYYOIoAAYvH0k20tvvgsQU',
    appId: '1:707196677230:android:df9d26942a0b9aa6fc0a7f',
    messagingSenderId: '707196677230',
    projectId: 'tik-tok-dani1552',
    storageBucket: 'tik-tok-dani1552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKwJA6mfDD5IW7y2YDlQVOoeGqQ8O-xO8',
    appId: '1:707196677230:ios:dfc3cd280b8b7803fc0a7f',
    messagingSenderId: '707196677230',
    projectId: 'tik-tok-dani1552',
    storageBucket: 'tik-tok-dani1552.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKwJA6mfDD5IW7y2YDlQVOoeGqQ8O-xO8',
    appId: '1:707196677230:ios:092189c321e03c12fc0a7f',
    messagingSenderId: '707196677230',
    projectId: 'tik-tok-dani1552',
    storageBucket: 'tik-tok-dani1552.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
